#pragma once

// handshake
// * one key per konvo generated by server
//
// -> user connects
// <- server responds with public key
//
// -> user sends its public key along with random number, encrypted with server public key
// <- server responds with random number encrypted using users public key
//
// -> user ack
// <- server responds with new public/private pair for session
//
enum connection_state {
    DISCONNECTED = 0,
    CONNECTED,
    HANDSHAKE_WAIT_SERVER_PUB,
    HANDSHAKE_CHALLENGE,
    HANDSHAKE_WAIT_SESSION_KEYS,
};
